[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S localhost:8080 -t public"

[variables]
PHP_VERSION = "8.2"
