services:
  - type: web
    name: tfa3camacho
    env: php
    plan: free
    startCommand: php -S localhost:8080 -t public
    envVars:
      - key: CI_ENVIRONMENT
        value: production
      - key: APP_BASEURL
        value: https://tfa3camacho.onrender.com